apiVersion: v1
kind: Namespace
metadata:
  name: fsdfsdsdfsfdffff-prod
  labels:
    environment-id: env_849b137b-4ddb-4c82-9adb-dce7988adf60
    project-id: project_c915428a-32e3-4270-a4e8-08f1b3b129bd
    project-name: fsdfsdsdfsfdffff
    environment-name: prod
    organization-id: org_e59ceffb-14d2-4f54-a93d-ed998cc11b2e
